[package]
name = "segment_engine"
version = "0.1.1"
edition = "2021"

[lib]
name = "segment_engine"
path = "src/lib.rs"

[dependencies]
cpal = "0.15.3"
rubato = "0.16.1"
symphonia = { version = "0.5.4", features = ["all-codecs"] }
uuid = { version = "1.16.0", features = ["v4"] }

[profile.release]
debug = true
