[package]
name = "shirabe"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
iced = {version = "0.13.1", features = ["tokio"]}
rfd = "0.15.3"
symphonia = {version = "0.5.4", features = ["all-codecs"]}

[profile.release]
debug = true
