[package]
name = "segment"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
crossbeam = "0.8.4"
rubato = "0.16.1"
symphonia = { version = "0.5.4", features = ["all-codecs"] }
uuid = { version = "1.16.0", features = ["v4"] }

[profile.release]
debug = true
